const memory = require('../memory');

class BuilderAgent {
  async execute(taskId) {
    const task = memory.getTask(taskId);
    console.log(`Builder agent working on task ${taskId}`);

    const prd = memory.loadArtifact('prds', taskId, 'prd.md');
    
    const htmlContent = `<!DOCTYPE html>
<html>
<head>
  <title>OPC Generated Project</title>
  <style>
    body { 
      font-family: Arial, sans-serif; 
      max-width: 800px; 
      margin: 0 auto; 
      padding: 20px; 
    }
    h1 { color: #333; }
    .goal { 
      background: #f0f8ff; 
      padding: 20px; 
      border-radius: 8px; 
      margin: 20px 0; 
    }
  </style>
</head>
<body>
  <h1>Generated Project</h1>
  <div class="goal">
    <h2>Goal</h2>
    <p>${task.goal}</p>
  </div>
  <p>This is a simple implementation generated by the OPC/Harness system.</p>
</body>
</html>`;

    const filePath = memory.saveArtifact('implementations', taskId, 'index.html', htmlContent);
    
    return {
      implementationPath: filePath,
      implementationContent: htmlContent,
      message: 'Implementation complete'
    };
  }
}

module.exports = BuilderAgent;
